user: ubuntu
private_key_path: ~/.ssh/id_ed25519
# private_key_content: |
#   -----BEGIN OPENSSH PRIVATE KEY-----
#   ...

port: 22
concurrency: 20

sudo: true

connect_timeout_seconds: 10
command_timeout_seconds: 900
max_output_bytes_per_stream: 262144

# known_hosts_path: ~/.ssh/known_hosts
strict_host_key_checking: false

command: |
  echo hello

hosts:
  - 1.2.3.4
  - example.com
